version: '3'

services:

  postgres:
    image: 'postgres:9.6-alpine'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  #    ports:
  #      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=documize
      - POSTGRES_USER=documize
      - POSTGRES_DB=documize

  documize:
    build:
      dockerfile: Dockerfile
      context: ./documize
    depends_on: 
      - postgres
    ports:
      - 5001:5001

  nginx:
    # restart: always
    depends_on: 
      - documize
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
      - ./nginxlog:/var/log/nginx
    ports: 
      - '8080:8080'